AA:1.000,AKs:1.000,AQs:1.000,AJs:1.000,ATs:1.000,A9s:1.000,A8s:1.000,A7s:1.000,A6s:1.000,A5s:1.000,A4s:1.000,A3s:1.000,A2s:1.000,AKo:1.000,KK:1.000,KQs:1.000,KJs:1.000,KTs:1.000,K9s:1.000,K8s:1.000,K7s:0.750,K6s:0.500,AQo:1.000,KQo:1.000,QQ:1.000,QJs:1.000,QTs:1.000,Q9s:1.000,Q8s:0.493,AJo:1.000,KJo:1.000,QJo:0.746,JJ:1.000,JTs:1.000,J9s:1.000,ATo:1.000,KTo:0.500,TT:1.000,T9s:1.000,A9o:0.649,99:1.000,98s:0.748,88:1.000,87s:0.750,77:1.000,76s:0.748,66:1.000,65s:0.700,55:1.000,44:0.748,33:0.650,22:0.649
